version: '3'

services:
  server:
    image: 'contractbuilder:latest'
    ports:
      - '3000:3000'
    environment:
      - 'TEMPLATE_DIRECTORY_LOCATION=/app/template'
    volumes:
      - './template:/app/template'